### PR TITLE
foodcritic 7 support

### PR DESCRIPTION
**Pull request by sinxcosx**
- foodcritic 7 support
- rubocop issues fixed
- tests are passing

### CODE REVIEW

**Comment by sinxcosx** [comment]
the travis build is using different ruby version that the one that is specific within the `.ruby-version`

**Comment by zuazo** [comment]
@sinxcosx, see my previous PR here: https://github.com/Nordstrom/guard-foodcritic/pull/19

**Comment by sinxcosx** [comment]
@suazo: i see it now. still haven't merged and no new version of the gem was published :(

**Comment by sinxcosx** [comment]
going to close this pull request as @zuazo already pushed his fix to the issue.

**Pull request closed without merging**
