### PR TITLE
Upgrade for Guard v2 API

### PR DESCRIPTION
**Pull request by jf647**
This is a very quick application of the upgrade instructions on the Guard Wiki here:

https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0

* change inheritance to be Guard::Plugin instead of Guard::Guard
* remove watchers array from constructor call in specs
* make runtime dependency on guard >= 2.0, <= 3.0

I didn't add any new tests, but all existing specs pass.

### CODE REVIEW

**Comment by jf647** [comment]
Any update on this?  We're still locking guard to old versions to get around this.

**Comment by logankoester** [comment]
Just tested locally, looks good to me.

**Comment by ericfode** [comment]
@cgriego are you still maintaining this repo? do you need a new owner?

**Comment by miketheman** [comment]
:+1:

**Comment by trickyearlobe** [comment]
I hadn't noticed that jf647 had added a pull request to switch to Guard 2.x API. I added a similar pull request, but for guard  >=2.9 we also have to fix the RSPEC tests by adding in guard-compat (see https://github.com/guard/guard/issues/693 for details).

Sorry about having 2 pulls with some overlap in content.

**Comment by billmoritz** [comment]
:+1:  This fixed my incompatibility issue..

**Comment by jf647** [comment]
Pinging for merge and release again.  If you don't have the time to maintain the gem going forward, Nordstrom is willing to adopt it - you can add me as collaborator (also jf647 on Rubygems) if you want.

**Comment by rlipke** [comment]
:+1: Cured a big gem dependency headache

**Comment by jf647** [comment]
If there's no activity on this, we're really close to forking and releasing an updated gem under a new name.  Can we please get a response from the maintainer as to whether this project has been abandoned?

To reiterate: Nordstrom is willing to take over maintenance of the gem if you want to transfer ownership to jf647 (both on Github and Rubygems)

Thanks

**Comment by kostyrevaa** [comment]
hey guys!
what's the status?

**Comment by jf647** [comment]
I have emailed Chris one last time asking to either merge the PR or transfer ownership to me.  If I don't hear back by 5/29, I am going to ask the rubygems admins to transfer the gem name to me, as to all appearances this is abandonware.

**Comment by jf647** [comment]
Looking at the rubygems forums, the admins don't seem to like force transferring, so I opened this discussion thread in the hopes that email from them might not be ignored:

http://help.rubygems.org/discussions/problems/21084-guard-foodcritic-abandoned-author-unresponsive

If that proves unhelpful, then fork and rename may be our only option, though that leaves the obvious first choice broken for the community.  Suggestions on what might be a good name that people might actually find are welcome.

**Comment by jf647** [comment]
The rubygems admins weighed in and as expected said they don't do forced transfers.  They suggested I try to raise Chris via Twitter, so I did:  https://twitter.com/jf647/status/603370853699493888

**Comment by jf647** [comment]
Quick update everyone: Chris transferred the repo and added me as collaborator on Rubygems, so I'll try to get a cleaned-up release with the PR out this weekend.

Thanks for following up, Chris.

**Comment by trickyearlobe** [comment]
Thanks Chris for transferring the ownership.

James, I'm going to cancel my PR but you may want to look at sorting out the tests as I had some issues. I think they were probably just down to me having different versions of Guard or RSpec.

**Comment by jf647** [comment]
Merged into upcoming release_1.10 branch

**Pull request closed without merging**
